Preserve data in json files
ismayito/school-library- pull request #6
Opened 2023-11-23 12:37 UTC by ismayito

### Preserve data in files in ruby
_______________________________________________________________________________________________________
#### Summary
_______________________________________________________________________________________________________
In this project, we added the following:
- preserved data into JSON files using ruby
- Loaded data from  json files on app load  using ruby
- Fix linter errors
- Followed gitflow

2023-11-23 12:57 UTC, DammyShittu reviewed
Hi @ismayito and @rmiyoyo,

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

### The second team member, @rmiyoyo, did not make a meaningful contribution to this project. He mostly only added comments which, while important, are relatively not as important as actual code.

### Also ensure rentals can be created seamlessly without the app crashing or having to quit the app and try again. All options should work at a go.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-11-23 19:41 UTC, rmiyoyo commented
# Work Done
- Fixed existing bugs and resubmitted for review.
- Data is saved; one per type of data stored and named accordingly.
- On startup the app loads all data from files.

2023-11-23 19:52 UTC, zeff96 requested changes
### Status: CHANGES REQUIRED ♻️
Hi @ismayito and @rmiyoyo , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media4.giphy.com/media/KyBesf8kNT6s88SEgb/200w.webp?cid=ecf05e47b30slf9sg2642kvs2pncotqk0tbot7pw9flu3qkv&ep=v1_gifs_search&rid=200w.webp&ct=g)

## Highlights
:heavy_check_mark: Linters passing
:heavy_check_mark: Descriptive PR



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-23 19:52 UTC, zeff96 commented on create_book.rb
> +    save_books_to_json(existing_books)
- [ ] Hey Team! 👋 Stellar job on implementing the method for saving books to JSON. 📚 However, there's a slight deviation from the project requirement. 🚧 According to the specifications, we're supposed to save to JSON only on app exit, not immediately upon book creation. 🔄 Kindly review the current implementation and make the necessary adjustments to align with the project's directive. Let's ensure we save that data only when the app bids us farewell. 🌟 Thanks for your attention to detail! 🙌

2023-11-23 19:52 UTC, zeff96 commented on create_rental.rb
> +  save_rentals_to_json(@rentals)
- [ ] Hey Team! 👋 Stellar job on implementing the method for saving rentals to JSON. 📚 However, there's a slight deviation from the project requirement. 🚧 According to the specifications, we're supposed to save to JSON only on app exit, not immediately upon rental creation. 🔄 Kindly review the current implementation and make the necessary adjustments to align with the project's directive. Let's ensure we save that data only when the app bids us farewell. 🌟 Thanks for your attention to detail! 🙌

2023-11-23 19:52 UTC, zeff96 commented on create_student.rb
> +  end
- [ ] Hey Team! 👋 Stellar job on implementing the method for saving person to JSON. 📚 However, there's a slight deviation from the project requirement. 🚧 According to the specifications, we're supposed to save to JSON only on app exit, not immediately upon person creation. 🔄 Kindly review the current implementation and make the necessary adjustments to align with the project's directive. Let's ensure we save that data only when the app bids us farewell. 🌟 Thanks for your attention to detail! 🙌

2023-11-23 19:52 UTC, zeff96 commented on create_teacher.rb
> +  end
- [ ] Hey Team! 👋 Stellar job on implementing the method for saving person to JSON. 📚 However, there's a slight deviation from the project requirement. 🚧 According to the specifications, we're supposed to save to JSON only on app exit, not immediately upon person creation. 🔄 Kindly review the current implementation and make the necessary adjustments to align with the project's directive. Let's ensure we save that data only when the app bids us farewell. 🌟 Thanks for your attention to detail! 🙌

2023-11-24 06:38 UTC, rmiyoyo commented
# Work Done After Review
- Data is now saved when user chooses to exit application

2023-11-24 06:53 UTC, binhussen approved these changes
Hi @Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
![IApproveSimonCowellGIF (6)](https://github.com/ismayito/school-library-/assets/52010789/04160276-c51d-4da2-b951-9685f8f43457)

## Highlights
- Preserved Data to Json file ✔️
- Well Starctured Code ✔️
- Used Git flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-24 06:54 UTC, merged